# Generated by Django 6.0.2 on 2026-09-27 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_alter_lugar_options_lugar_compartidos_lugar_horario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud_turista', models.FloatField()),
                ('longitud_turista', models.FloatField()),
                ('distancia_metros', models.FloatField(help_text='Distancia geodésica calculada en metros')),
                ('fecha_visita', models.DateField(default=django.utils.timezone.now)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_verificadas', to='turismo.lugar')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita Física Verificada',
                'verbose_name_plural': 'Visitas Físicas Verificadas',
                'unique_together': {('lugar', 'usuario', 'fecha_visita')},
            },
        ),
    ]
