# Generated by Django 6.0.2 on 2026-09-27 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0004_visitafisica'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionTendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proyectada', models.DateField()),
                ('afluencia_estimada', models.PositiveIntegerField(help_text='Estimación de visitantes proyectados')),
                ('nivel_demanda', models.CharField(default='Media', max_length=20)),
                ('accion_prescriptiva', models.TextField(blank=True, help_text='Sugerencia de gestión para la municipalidad')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='turismo.lugar')),
            ],
            options={
                'verbose_name': 'Predicción de Tendencia',
                'verbose_name_plural': 'Predicciones de Tendencias',
                'ordering': ['fecha_proyectada', '-afluencia_estimada'],
            },
        ),
    ]
